// Playbeat Digital Store — central configuration

export type CategoryConfig = {
  id: string;
  name: string;
  icon: string;
  gradient: string;
  blurb: string;
};

export const CATEGORIES: CategoryConfig[] = [
  {
    id: "call-of-duty-mobile",
    name: "Call of Duty Mobile",
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    blurb: "CP points top-up",
  },
  {
    id: "free-fire-max",
    name: "Free Fire MAX",
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    blurb: "Diamonds & memberships",
  },
  {
    id: "free-fire",
    name: "Free Fire",
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    blurb: "Diamonds & gift cards",
  },
  {
    id: "league-wild-rift",
    name: "LoL Wild Rift",
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    blurb: "Wild Cores top-up",
  },
  {
    id: "mobile-legends",
    name: "Mobile Legends",
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    blurb: "M-Cash & diamonds",
  },
  {
    id: "pubg-mobile",
    name: "PUBG Mobile",
    icon: "Gamepad2",
    gradient: "from-amber-500/80 to-orange-600/80",
    blurb: "UC top-up & gift cards",
  },
  {
    id: "steam-wallet",
    name: "Steam Wallet",
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    blurb: "Steam gift card codes",
  },
];

export function getCategory(id: string): CategoryConfig | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export const ADMIN_EMAILS = [
  "admin@playbeat.live",
  "owner@playbeat.live",
];

export const STORE = {
  name: "Playbeat Digital Store",
  tagline: "Gaming top-ups & gift cards, delivered instantly — worldwide.",
  currency: "USD",
  supportEmail: "support@playbeat.live",
  tickerItems: [
    "Instant digital delivery",
    "Secure Bank Alfalah checkout · Visa · Mastercard",
    "Worldwide activation",
    "24/7 customer support",
    "PUBG · Call of Duty · Free Fire · Steam",
    "Best prices on game top-ups",
  ],
};

export type SeedProduct = {
  name: string;
  slug: string;
  description: string;
  category: string;
  brand: string;
  price: number;
  oldPrice?: number;
  badge?: string;
  icon: string;
  gradient: string;
  image?: string;
  stock: number;
  featured?: boolean;
};

// Category-level product images (web-sourced, OSS-hosted).
export const PRODUCT_IMAGES: Record<string, string> = {
  "pubg-mobile": "https://sfile.chatglm.cn/images-ppt/ea483afef209.jpg",
  "call-of-duty-mobile": "https://sfile.chatglm.cn/images-ppt/d3f59454854d.jpg",
  "free-fire": "https://sfile.chatglm.cn/images-ppt/10963b9adce0.jpg",
  "free-fire-max": "https://sfile.chatglm.cn/images-ppt/b5a710391293.jpg",
  "league-wild-rift": "https://sfile.chatglm.cn/images-ppt/5d9ba6900c7c.jpg",
  "mobile-legends": "https://sfile.chatglm.cn/images-ppt/2eb81dc27055.jpg",
  "steam-wallet": "https://sfile.chatglm.cn/images-ppt/9838c3cf533d.jpg",
};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    name: "31 CP",
    slug: "call-of-duty-mobile-31-cp",
    description: "31 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 0.98,
    oldPrice: 0.93,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: true,
  },
  {
    name: "62 CP",
    slug: "call-of-duty-mobile-62-cp",
    description: "62 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 0.98,
    oldPrice: 0.93,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "420 CP",
    slug: "call-of-duty-mobile-420-cp",
    description: "420 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 5.93,
    oldPrice: 5.65,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "800 CP",
    slug: "call-of-duty-mobile-800-cp",
    description: "800 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 11.25,
    oldPrice: 10.71,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "2,059 CP",
    slug: "call-of-duty-mobile-2-059-cp",
    description: "2,059 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 20.88,
    oldPrice: 19.89,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "3,564 CP",
    slug: "call-of-duty-mobile-3-564-cp",
    description: "3,564 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 34.02,
    oldPrice: 32.4,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "7,656 CP",
    slug: "call-of-duty-mobile-7-656-cp",
    description: "7,656 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 118.79,
    oldPrice: 113.13,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "38,280 CP",
    slug: "call-of-duty-mobile-38-280-cp",
    description: "38,280 CP — CP points top-up. Instant delivery to your account.",
    category: "call-of-duty-mobile",
    brand: "Mamang243",
    price: 354.64,
    oldPrice: 337.75,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-green-600/80 to-emerald-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "110 Diamonds",
    slug: "free-fire-max-110-diamonds",
    description: "110 Diamonds — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "MBDOMINGUEZ",
    price: 3.15,
    oldPrice: 3,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Weekly Membership",
    slug: "free-fire-max-weekly-membership",
    description: "Weekly Membership — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "Abdulstoree",
    price: 5.97,
    oldPrice: 5.69,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "645 Diamonds",
    slug: "free-fire-max-645-diamonds",
    description: "645 Diamonds — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "ONKIOSTORE",
    price: 8.47,
    oldPrice: 8.07,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "1,450 Diamonds",
    slug: "free-fire-max-1-450-diamonds",
    description: "1,450 Diamonds — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "MysFcm",
    price: 10.45,
    oldPrice: 9.95,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Monthly Membership",
    slug: "free-fire-max-monthly-membership",
    description: "Monthly Membership — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "CTG_Gm_ShOp",
    price: 10.92,
    oldPrice: 10.4,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "2,180 Diamonds",
    slug: "free-fire-max-2-180-diamonds",
    description: "2,180 Diamonds — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "CTG_Gm_ShOp",
    price: 19.94,
    oldPrice: 18.99,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "4,450 Diamonds",
    slug: "free-fire-max-4-450-diamonds",
    description: "4,450 Diamonds — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "ONKIOSTORE",
    price: 60.89,
    oldPrice: 57.99,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "6,900 Diamonds",
    slug: "free-fire-max-6-900-diamonds",
    description: "6,900 Diamonds — Diamonds & memberships. Instant delivery to your account.",
    category: "free-fire-max",
    brand: "ONKIOSTORE",
    price: 85.28,
    oldPrice: 81.22,
    badge: undefined,
    icon: "Flame",
    gradient: "from-rose-500/80 to-pink-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire - Garena Diamonds 100 (LATAM)",
    slug: "free-fire-free-fire-garena-diamonds-100-latam",
    description: "Free Fire - Garena Diamonds 100 (LATAM) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "PinesDigital",
    price: 1.05,
    oldPrice: 1,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire Gift Card 100 +10 Diamonds (Global)",
    slug: "free-fire-free-fire-gift-card-100-10-diamonds-global",
    description: "Free Fire Gift Card 100 +10 Diamonds (Global) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "FASTYANG",
    price: 1.37,
    oldPrice: 1.3,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire Gift Card 210 + 21 Diamonds (US)",
    slug: "free-fire-free-fire-gift-card-210-21-diamonds-us",
    description: "Free Fire Gift Card 210 + 21 Diamonds (US) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "GameKongs",
    price: 2.26,
    oldPrice: 2.15,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire - Garena Diamonds 210 + 53 (TR+EU)",
    slug: "free-fire-free-fire-garena-diamonds-210-53-tr-eu",
    description: "Free Fire - Garena Diamonds 210 + 53 (TR+EU) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "FASTYANG",
    price: 2.52,
    oldPrice: 2.4,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire Gift Card 530 + 53 Diamonds (Global)",
    slug: "free-fire-free-fire-gift-card-530-53-diamonds-global",
    description: "Free Fire Gift Card 530 + 53 Diamonds (Global) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "FASTYANG",
    price: 5.66,
    oldPrice: 5.39,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire - Garena Diamonds 1,080 (MENA)",
    slug: "free-fire-free-fire-garena-diamonds-1-080-mena",
    description: "Free Fire - Garena Diamonds 1,080 (MENA) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "hossain_city",
    price: 9.97,
    oldPrice: 9.5,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire Gift Card 1,080 Diamonds (Global)",
    slug: "free-fire-free-fire-gift-card-1-080-diamonds-global",
    description: "Free Fire Gift Card 1,080 Diamonds (Global) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "ONKIOSTORE",
    price: 11.57,
    oldPrice: 11.02,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Free Fire Gift Card 2,200 + 220 Diamonds (Global)",
    slug: "free-fire-free-fire-gift-card-2-200-220-diamonds-global",
    description: "Free Fire Gift Card 2,200 + 220 Diamonds (Global) — Diamonds & gift cards. Instant delivery to your account.",
    category: "free-fire",
    brand: "ArgenGaming",
    price: 22.64,
    oldPrice: 21.56,
    badge: undefined,
    icon: "Flame",
    gradient: "from-orange-500/80 to-red-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "105 Wild Cores",
    slug: "league-wild-rift-105-wild-cores",
    description: "105 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "dailyshopaja",
    price: 1.07,
    oldPrice: 1.02,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "425 Wild Cores",
    slug: "league-wild-rift-425-wild-cores",
    description: "425 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "NexusGalaxy",
    price: 3.33,
    oldPrice: 3.17,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "585 Wild Cores",
    slug: "league-wild-rift-585-wild-cores",
    description: "585 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "dailyshopaja",
    price: 5.31,
    oldPrice: 5.06,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "1,000 Wild Cores",
    slug: "league-wild-rift-1-000-wild-cores",
    description: "1,000 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "NexusGalaxy",
    price: 7.43,
    oldPrice: 7.08,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "1,135 Wild Cores",
    slug: "league-wild-rift-1-135-wild-cores",
    description: "1,135 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "dailyshopaja",
    price: 10.09,
    oldPrice: 9.61,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "1,660 Wild Cores",
    slug: "league-wild-rift-1-660-wild-cores",
    description: "1,660 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "dailyshopaja",
    price: 13.98,
    oldPrice: 13.31,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "3,010 Wild Cores",
    slug: "league-wild-rift-3-010-wild-cores",
    description: "3,010 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "dailyshopaja",
    price: 22.63,
    oldPrice: 21.55,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "3,330 Wild Cores",
    slug: "league-wild-rift-3-330-wild-cores",
    description: "3,330 Wild Cores — Wild Cores top-up. Instant delivery to your account.",
    category: "league-wild-rift",
    brand: "dailyshopaja",
    price: 26.81,
    oldPrice: 25.53,
    badge: undefined,
    icon: "Sword",
    gradient: "from-blue-600/80 to-indigo-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "132 M-Cash",
    slug: "mobile-legends-132-m-cash",
    description: "132 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "dragonsong",
    price: 1.62,
    oldPrice: 1.54,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "411 M-Cash",
    slug: "mobile-legends-411-m-cash",
    description: "411 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "dragonsong",
    price: 4.18,
    oldPrice: 3.98,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "1,499 M-Cash",
    slug: "mobile-legends-1-499-m-cash",
    description: "1,499 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "Mamang243",
    price: 15.42,
    oldPrice: 14.69,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "1,999 M-Cash",
    slug: "mobile-legends-1-999-m-cash",
    description: "1,999 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "HQStore247",
    price: 21.95,
    oldPrice: 20.9,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "2,999 M-Cash",
    slug: "mobile-legends-2-999-m-cash",
    description: "2,999 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "Mamang243",
    price: 31.64,
    oldPrice: 30.13,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "5,000 M-Cash",
    slug: "mobile-legends-5-000-m-cash",
    description: "5,000 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "dragonsong",
    price: 50.75,
    oldPrice: 48.33,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "10,000 M-Cash",
    slug: "mobile-legends-10-000-m-cash",
    description: "10,000 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "dragonsong",
    price: 101.5,
    oldPrice: 96.67,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "32,999 M-Cash",
    slug: "mobile-legends-32-999-m-cash",
    description: "32,999 M-Cash — M-Cash & diamonds. Instant delivery to your account.",
    category: "mobile-legends",
    brand: "Mamang243",
    price: 314.52,
    oldPrice: 299.54,
    badge: undefined,
    icon: "Users",
    gradient: "from-violet-600/80 to-purple-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "25 UC",
    slug: "pubg-mobile-25-uc",
    description: "25 UC — UC top-up & gift cards. Instant delivery to your account.",
    category: "pubg-mobile",
    brand: "ExploreShop",
    price: 0.53,
    oldPrice: 0.5,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-amber-500/80 to-orange-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "60 UC",
    slug: "pubg-mobile-60-uc",
    description: "60 UC — UC top-up & gift cards. Instant delivery to your account.",
    category: "pubg-mobile",
    brand: "mommo06",
    price: 0.82,
    oldPrice: 0.78,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-amber-500/80 to-orange-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "63 UC",
    slug: "pubg-mobile-63-uc",
    description: "63 UC — UC top-up & gift cards. Instant delivery to your account.",
    category: "pubg-mobile",
    brand: "kalbarGS",
    price: 0.89,
    oldPrice: 0.85,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-amber-500/80 to-orange-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "36 UC",
    slug: "pubg-mobile-36-uc",
    description: "36 UC — UC top-up & gift cards. Instant delivery to your account.",
    category: "pubg-mobile",
    brand: "Mamang243",
    price: 1.03,
    oldPrice: 0.98,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-amber-500/80 to-orange-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code TRY 15 (TR)",
    slug: "steam-wallet-steam-wallet-code-try-15-tr",
    description: "Steam Wallet Code TRY 15 (TR) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "Ar1se_store",
    price: 0.53,
    oldPrice: 0.5,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code ARS 500 (AR)",
    slug: "steam-wallet-steam-wallet-code-ars-500-ar",
    description: "Steam Wallet Code ARS 500 (AR) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "StoreFortr",
    price: 0.89,
    oldPrice: 0.85,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code IDR 6,000 (ID)",
    slug: "steam-wallet-steam-wallet-code-idr-6-000-id",
    description: "Steam Wallet Code IDR 6,000 (ID) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "Phoebos",
    price: 0.93,
    oldPrice: 0.89,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code TRY 20 (TR)",
    slug: "steam-wallet-steam-wallet-code-try-20-tr",
    description: "Steam Wallet Code TRY 20 (TR) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "StoreFortr",
    price: 0.99,
    oldPrice: 0.94,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code USD 1 (EC)",
    slug: "steam-wallet-steam-wallet-code-usd-1-ec",
    description: "Steam Wallet Code USD 1 (EC) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "TyGokuri",
    price: 1.05,
    oldPrice: 1,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code CNY 5 (CN)",
    slug: "steam-wallet-steam-wallet-code-cny-5-cn",
    description: "Steam Wallet Code CNY 5 (CN) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "WoodrowW",
    price: 1.12,
    oldPrice: 1.07,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code MYR 5 (MY)",
    slug: "steam-wallet-steam-wallet-code-myr-5-my",
    description: "Steam Wallet Code MYR 5 (MY) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "Phoebos",
    price: 1.35,
    oldPrice: 1.29,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Wallet Code JPY 110 (JP)",
    slug: "steam-wallet-steam-wallet-code-jpy-110-jp",
    description: "Steam Wallet Code JPY 110 (JP) — Steam gift card codes. Instant delivery to your account.",
    category: "steam-wallet",
    brand: "WoodrowW",
    price: 1.56,
    oldPrice: 1.49,
    badge: undefined,
    icon: "Gift",
    gradient: "from-slate-600/80 to-gray-700/80",
    stock: 999,
    featured: false,
  },
].map((p) => ({ ...p, image: PRODUCT_IMAGES[p.category] }));

// ── Trending Items (from items.html) ─────────────────────────────────────
export type TrendingItem = {
  name: string;
  slug: string;
  description: string;
  category: string;
  brand: string;
  price: number;
  badge?: string;
  icon: string;
  gradient: string;
  image: string;
  stock: number;
  featured: boolean;
  sales: number;
};

export const TRENDING_ITEMS: TrendingItem[] = [
  {
    name: "ARC Raiders",
    slug: "item-arc-raiders",
    description: "ARC Raiders is a free-to-play, extraction shooter set in a sci-fi world. Team up to take on alien threats.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-red-500/80 to-orange-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/faf6333bf8fb.jpg",
    stock: 999,
    featured: true,
    sales: 39794,
  },
  {
    name: "RBL",
    slug: "item-rbl",
    description: "RBL — competitive baseball game with real-time multiplayer matches and team management.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-purple-600/80 to-violet-700/80",
    image: "https://sfile.chatglm.cn/images-ppt/a0210a6f6244.jpg",
    stock: 999,
    featured: true,
    sales: 135682,
  },
  {
    name: "Valorant",
    slug: "item-valorant",
    description: "Valorant — tactical 5v5 character shooter from Riot Games. Precise gunplay meets unique agent abilities.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    badge: undefined,
    icon: "Crosshair",
    gradient: "from-amber-500/80 to-red-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/7d34f4925daf.jpg",
    stock: 999,
    featured: true,
    sales: 55,
  },
  {
    name: "Diablo 2: Resurrected",
    slug: "item-diablo-2-resurrected",
    description: "Diablo II Resurrected — the classic action RPG remastered. Hunt loot, slay demons across 5 acts.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    icon: "Skull",
    gradient: "from-red-800/80 to-rose-900/80",
    image: "https://sfile.chatglm.cn/images-ppt/0dabdf85c125.jpg",
    stock: 999,
    featured: true,
    sales: 144853,
  },
  {
    name: "Diablo 4",
    slug: "item-diablo-4",
    description: "Diablo IV — return to Sanctuary in the ultimate action RPG. Open world, shared world bosses, endless endgame.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    icon: "Skull",
    gradient: "from-red-900/80 to-stone-800/80",
    image: "https://sfile.chatglm.cn/images-ppt/6235ecbd64b0.jpg",
    stock: 999,
    featured: true,
    sales: 99948,
  },
  {
    name: "Warframe",
    slug: "item-warframe",
    description: "Warframe — free-to-play cooperative third-person shooter. Ninja-style space combat with 40+ frames.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    badge: undefined,
    icon: "Zap",
    gradient: "from-yellow-500/80 to-amber-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/496902445446.png",
    stock: 999,
    featured: true,
    sales: 16952,
  },
  {
    name: "Clash of Clans",
    slug: "item-clash-of-clans",
    description: "Clash of Clans — build your village, train troops, and battle millions of players worldwide.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    badge: undefined,
    icon: "Sword",
    gradient: "from-green-600/80 to-emerald-700/80",
    image: "https://sfile.chatglm.cn/images-ppt/45c5d5f11937.jpeg",
    stock: 999,
    featured: true,
    sales: 6967,
  },
  {
    name: "Growtopia",
    slug: "item-growtopia",
    description: "Growtopia — 2D sandbox MMO where you build, mine, craft, and trade with players around the world.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    badge: undefined,
    icon: "Sprout",
    gradient: "from-lime-500/80 to-green-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/2a6395b4c27d.jpg",
    stock: 999,
    featured: true,
    sales: 5431,
  },
];
