// Playbeat Digital Store — central configuration

export type CategoryConfig = {
  id: string;
  name: string;
  icon: string;
  gradient: string;
  blurb: string;
};

export const CATEGORIES: CategoryConfig[] = [
  {
    id: "streaming",
    name: "Streaming",
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    blurb: "Netflix, Spotify, YouTube & more",
  },
  {
    id: "memberships",
    name: "Memberships",
    icon: "Users",
    gradient: "from-amber-600/80 to-orange-600/80",
    blurb: "IPTV & premium memberships",
  },
  {
    id: "ai-tools",
    name: "AI Tools",
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    blurb: "ChatGPT, Claude, Midjourney & more",
  },
  {
    id: "software",
    name: "Software",
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    blurb: "Windows, Office, VPNs & licenses",
  },
];

export function getCategory(id: string): CategoryConfig | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export const ADMIN_EMAILS = ["admin@playbeat.digital"];

export const STORE = {
  name: "Playbeat Digital Store",
  tagline: "Streaming, AI tools, software licenses & more — delivered instantly.",
  currency: "PKR",
  supportEmail: "info@playbeat.digital",
  tickerItems: [
    "Instant digital delivery",
    "Secure checkout · JazzCash · Bank Alfalah",
    "Worldwide activation",
    "24/7 customer support",
    "Netflix · Spotify · ChatGPT · Windows",
    "Best prices in Pakistan",
  ],
};

export type SeedProduct = {
  name: string;
  slug: string;
  description: string;
  category: string;
  brand: string;
  price: number;
  oldPrice?: number;
  badge?: string;
  icon: string;
  gradient: string;
  image?: string;
  stock: number;
  featured?: boolean;
};

export const PRODUCT_IMAGES: Record<string, string> = {};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    name: "YouTube Premium",
    slug: "youtube-premium",
    description: "YouTube Premium — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 418,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: true,
  },
  {
    name: "GEO IPTV",
    slug: "geo-iptv",
    description: "GEO IPTV — instant activation. Delivered to your email within minutes.",
    category: "memberships",
    brand: "Playbeat",
    price: 499,
    icon: "Users",
    gradient: "from-amber-600/80 to-orange-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Netflix Premium 4K",
    slug: "netflix-premium-4k",
    description: "Netflix Premium 4K — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 976,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Spotify Premium",
    slug: "spotify-premium",
    description: "Spotify Premium — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 698,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: true,
  },
  {
    name: "ChatGPT Plus",
    slug: "chatgpt-plus",
    description: "ChatGPT Plus — instant activation. Delivered to your email within minutes.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 2232,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Amazon Prime Video",
    slug: "amazon-prime-video",
    description: "Amazon Prime Video — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 698,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Netflix Standard 1080p",
    slug: "netflix-standard-1080p",
    description: "Netflix Standard 1080p — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 781,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Disney+ Premium 4K",
    slug: "disney-premium-4k",
    description: "Disney+ Premium 4K — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 837,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "HBO Max",
    slug: "hbo-max",
    description: "HBO Max — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 558,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Hulu (No Ads)",
    slug: "hulu-no-ads",
    description: "Hulu (No Ads) — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 698,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Crunchyroll Mega Fan",
    slug: "crunchyroll-mega-fan",
    description: "Crunchyroll Mega Fan — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 4185,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Claude Pro",
    slug: "claude-pro",
    description: "Claude Pro — instant activation. Delivered to your email within minutes.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 2372,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    description: "Midjourney — instant activation. Delivered to your email within minutes.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 2790,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Canva Pro",
    slug: "canva-pro",
    description: "Canva Pro — instant activation. Delivered to your email within minutes.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 558,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Grammarly Premium",
    slug: "grammarly-premium",
    description: "Grammarly Premium — instant activation. Delivered to your email within minutes.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 976,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Jasper AI",
    slug: "jasper-ai",
    description: "Jasper AI — instant activation. Delivered to your email within minutes.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 3348,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "ExpressVPN",
    slug: "expressvpn",
    description: "ExpressVPN — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 1674,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "NordVPN",
    slug: "nordvpn",
    description: "NordVPN — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 1116,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Windows 11 Pro",
    slug: "windows-11-pro",
    description: "Windows 11 Pro — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 698,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Windows 11 Home",
    slug: "windows-11-home",
    description: "Windows 11 Home — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 614,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Windows 10 Pro",
    slug: "windows-10-pro",
    description: "Windows 10 Pro — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 558,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Windows 10 Home",
    slug: "windows-10-home",
    description: "Windows 10 Home — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 502,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Microsoft Office 2021 Pro Plus",
    slug: "microsoft-office-2021-pro-plus",
    description: "Microsoft Office 2021 Pro Plus — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 1534,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Microsoft Office 2019 Pro Plus",
    slug: "microsoft-office-2019-pro-plus",
    description: "Microsoft Office 2019 Pro Plus — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 1116,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Adobe Creative Cloud",
    slug: "adobe-creative-cloud",
    description: "Adobe Creative Cloud — instant activation. Delivered to your email within minutes.",
    category: "software",
    brand: "Playbeat",
    price: 2790,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Microsoft 365 Family",
    slug: "microsoft-365-family",
    description: "Microsoft 365 Family — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 1958,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Google One 2TB",
    slug: "google-one-2tb",
    description: "Google One 2TB — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 837,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "iCloud+ 2TB",
    slug: "icloud-2tb",
    description: "iCloud+ 2TB — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 698,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Discord Nitro",
    slug: "discord-nitro",
    description: "Discord Nitro — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 976,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Telegram Premium",
    slug: "telegram-premium",
    description: "Telegram Premium — instant activation. Delivered to your email within minutes.",
    category: "streaming",
    brand: "Playbeat",
    price: 558,
    icon: "Play",
    gradient: "from-red-600/80 to-rose-700/80",
    stock: 999,
    featured: false,
  },
];

export type TrendingItem = {
  name: string;
  slug: string;
  description: string;
  category: string;
  brand: string;
  price: number;
  badge?: string;
  icon: string;
  gradient: string;
  image: string;
  stock: number;
  featured: boolean;
  sales: number;
};

export const TRENDING_ITEMS: TrendingItem[] = [
  {
    name: "ARC Raiders",
    slug: "item-arc-raiders",
    description: "ARC Raiders is a free-to-play, extraction shooter set in a sci-fi world.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    icon: "Gamepad2",
    gradient: "from-red-500/80 to-orange-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/faf6333bf8fb.jpg",
    stock: 999,
    featured: true,
    sales: 39794,
  },
  {
    name: "RBL",
    slug: "item-rbl",
    description: "Competitive baseball game with real-time multiplayer matches.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    icon: "Crosshair",
    gradient: "from-purple-600/80 to-violet-700/80",
    image: "https://sfile.chatglm.cn/images-ppt/a0210a6f6244.jpg",
    stock: 999,
    featured: true,
    sales: 135682,
  },
  {
    name: "Valorant",
    slug: "item-valorant",
    description: "Tactical 5v5 character shooter from Riot Games.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    icon: "Crosshair",
    gradient: "from-amber-500/80 to-red-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/7d34f4925daf.jpg",
    stock: 999,
    featured: true,
    sales: 55,
  },
  {
    name: "Diablo 2: Resurrected",
    slug: "item-diablo-2-resurrected",
    description: "The classic action RPG remastered. Hunt loot, slay demons.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    icon: "Skull",
    gradient: "from-red-800/80 to-rose-900/80",
    image: "https://sfile.chatglm.cn/images-ppt/0dabdf85c125.jpg",
    stock: 999,
    featured: true,
    sales: 144853,
  },
  {
    name: "Diablo 4",
    slug: "item-diablo-4",
    description: "Return to Sanctuary in the ultimate action RPG.",
    category: "items",
    brand: "Playbeat Arena",
    price: 13,
    icon: "Skull",
    gradient: "from-red-900/80 to-stone-800/80",
    image: "https://sfile.chatglm.cn/images-ppt/6235ecbd64b0.jpg",
    stock: 999,
    featured: true,
    sales: 99948,
  },
  {
    name: "Warframe",
    slug: "item-warframe",
    description: "Free-to-play cooperative third-person shooter.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    icon: "Zap",
    gradient: "from-yellow-500/80 to-amber-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/496902445446.png",
    stock: 999,
    featured: true,
    sales: 16952,
  },
  {
    name: "Clash of Clans",
    slug: "item-clash-of-clans",
    description: "Build your village, train troops, and battle millions of players.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    icon: "Sword",
    gradient: "from-green-600/80 to-emerald-700/80",
    image: "https://sfile.chatglm.cn/images-ppt/45c5d5f11937.jpeg",
    stock: 999,
    featured: true,
    sales: 6967,
  },
  {
    name: "Growtopia",
    slug: "item-growtopia",
    description: "2D sandbox MMO where you build, mine, craft, and trade.",
    category: "items",
    brand: "Playbeat Arena",
    price: 10,
    icon: "Sprout",
    gradient: "from-lime-500/80 to-green-600/80",
    image: "https://sfile.chatglm.cn/images-ppt/2a6395b4c27d.jpg",
    stock: 999,
    featured: true,
    sales: 5431,
  },
];

