// Playbeat Digital Store — central configuration

export type CategoryConfig = {
  id: string;
  name: string;
  icon: string; // lucide icon name
  gradient: string; // tailwind gradient classes for artwork
  blurb: string;
};

export const CATEGORIES: CategoryConfig[] = [
  {
    id: "ai-tools",
    name: "AI Tools",
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    blurb: "AI writers, image gen, voice tools",
  },
  {
    id: "software",
    name: "Software",
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    blurb: "Licenses & dev tools",
  },
  {
    id: "subscriptions",
    name: "SaaS",
    icon: "Crown",
    gradient: "from-amber-500/80 to-yellow-500/80",
    blurb: "Recurring software subs",
  },
  {
    id: "digital-downloads",
    name: "Downloads",
    icon: "Download",
    gradient: "from-pink-500/80 to-purple-600/80",
    blurb: "Music, LUTs, assets",
  },
  {
    id: "e-books",
    name: "E-Books",
    icon: "BookOpen",
    gradient: "from-sky-500/80 to-indigo-600/80",
    blurb: "Guides & playbooks",
  },
  {
    id: "templates",
    name: "Templates",
    icon: "Layout",
    gradient: "from-violet-500/80 to-fuchsia-600/80",
    blurb: "Landing pages & decks",
  },
  {
    id: "graphics",
    name: "Graphics",
    icon: "Palette",
    gradient: "from-rose-500/80 to-orange-500/80",
    blurb: "Icons, presets, logos",
  },
  {
    id: "courses",
    name: "Courses",
    icon: "GraduationCap",
    gradient: "from-blue-500/80 to-cyan-600/80",
    blurb: "Learn to build & ship",
  },
  {
    id: "memberships",
    name: "Memberships",
    icon: "Users",
    gradient: "from-amber-600/80 to-orange-600/80",
    blurb: "Community & founder access",
  },
  {
    id: "payment-gateways",
    name: "Payment Gateways",
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    blurb: "Stripe, PayPal, Paddle kits",
  },
  {
    id: "games",
    name: "Games",
    icon: "Gamepad2",
    gradient: "from-violet-600/80 to-fuchsia-600/80",
    blurb: "Indie game keys",
  },
  {
    id: "gift-cards",
    name: "Gift Cards",
    icon: "Gift",
    gradient: "from-rose-500/80 to-orange-500/80",
    blurb: "Steam, Netflix, Spotify, Amazon",
  },
];

export function getCategory(id: string): CategoryConfig | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

// Admin whitelisted emails (admin panel access)
export const ADMIN_EMAILS = [
  "admin@playbeat.live",
  "owner@playbeat.live",
];

export const STORE = {
  name: "Playbeat Digital Store",
  tagline: "Digital products, delivered instantly — worldwide.",
  currency: "USD",
  supportEmail: "support@playbeat.live",
  tickerItems: [
    "Instant digital delivery",
    "Secure PayFast checkout · Visa · Mastercard · RAAST · 3D Secure",
    "Worldwide activation",
    "24/7 customer support",
    "AI tools, SaaS, templates, courses & more",
    "Stripe · PayPal · Paddle · Steam · Netflix",
  ],
};

export type SeedProduct = {
  name: string;
  slug: string;
  description: string;
  category: string;
  brand: string;
  price: number;
  oldPrice?: number;
  badge?: string;
  icon: string;
  gradient: string;
  image?: string;
  stock: number;
  featured?: boolean;
};

// Real product images (web-sourced, OSS-hosted, guaranteed reachable).
// Frontend falls back to the gradient+icon artwork if a URL fails to load.
export const PRODUCT_IMAGES: Record<string, string> = {
  "novascript-ai-writer": "https://sfile.chatglm.cn/images-ppt/46da42d9a044.png",
  "pixelforge-image-generator": "https://sfile.chatglm.cn/images-ppt/305d15ba79b3.jpeg",
  "voxai-voice-cloning-suite": "https://sfile.chatglm.cn/images-ppt/d448df3fe240.jpg",
  "devguard-pro-license": "https://sfile.chatglm.cn/images-ppt/43cf34c266f4.jpg",
  "sheetflow-automation": "https://sfile.chatglm.cn/images-ppt/31543c69ab5c.png",
  "inboxzen-email-marketing": "https://sfile.chatglm.cn/images-ppt/d5217e69dc80.png",
  "cinemaster-luts-bundle": "https://sfile.chatglm.cn/images-ppt/00add3b64454.jpg",
  "the-indie-maker-playbook": "https://sfile.chatglm.cn/images-ppt/6552ec56ecc9.png",
  "launchkit-landing-templates": "https://sfile.chatglm.cn/images-ppt/4db6bec0e3d9.jpg",
  "aurora-icon-set": "https://sfile.chatglm.cn/images-ppt/f6bd7dff7943.png",
  "mastering-prompt-engineering": "https://sfile.chatglm.cn/images-ppt/34407e1f87f6.jpg",
  "founders-circle-membership": "https://sfile.chatglm.cn/images-ppt/f4a749345d1b.png",
  "datawave-analytics-platform": "https://sfile.chatglm.cn/images-ppt/e2bced056e90.png",
  "synthwave-music-pack": "https://sfile.chatglm.cn/images-ppt/c08d6259797f.jpg",
  "cloudvault-backup-license": "https://sfile.chatglm.cn/images-ppt/ba1e783546a7.jpg",
  "briefbot-ai-assistant": "https://sfile.chatglm.cn/images-ppt/31b66408250f.jpg",
  "resumeboost-ai-tool": "https://sfile.chatglm.cn/images-ppt/2bb918cd3961.jpg",
  "pitchdeck-pro-templates": "https://sfile.chatglm.cn/images-ppt/06cc8a306f81.jpg",
  "codecraft-design-patterns": "https://sfile.chatglm.cn/images-ppt/32029b79de13.jpg",
  "photofx-lightroom-presets": "https://sfile.chatglm.cn/images-ppt/deb8fa18a62c.jpg",
  "web3-dev-bootcamp": "https://sfile.chatglm.cn/images-ppt/f40e0424356e.jpg",
  "taskflow-pm-tool": "https://sfile.chatglm.cn/images-ppt/e726eb7c1a18.png",
  "renderfarm-gpu-credits": "https://sfile.chatglm.cn/images-ppt/412403417a63.jpg",
  "brandkit-logo-bundle": "https://sfile.chatglm.cn/images-ppt/42cd0ffcaa67.jpg",
  "stripe-connect-integration-kit": "https://sfile.chatglm.cn/images-ppt/eeb459f8ae0a.png",
  "paypal-checkout-pro": "https://sfile.chatglm.cn/images-ppt/72508d6c5800.jpg",
  "paddle-billing-suite": "https://sfile.chatglm.cn/images-ppt/358c9bee03fb.png",
  "lemon-squeezy-storefront-pack": "https://sfile.chatglm.cn/images-ppt/b1282f1b8133.jpg",
  "cryptopay-gateway": "https://sfile.chatglm.cn/images-ppt/6e2ca1a139c0.jpg",
  "razorpay-route-integration": "https://sfile.chatglm.cn/images-ppt/04a0f34fec93.png",
  "neon-drift-racer": "https://sfile.chatglm.cn/images-ppt/0dcd4e3ec12e.png",
  "dungeon-of-aether": "https://sfile.chatglm.cn/images-ppt/273983ca66b3.jpg",
  "pixel-kingdom-builder-kit": "https://sfile.chatglm.cn/images-ppt/80c4e54fa133.jpg",
  "starbound-tactics": "https://sfile.chatglm.cn/images-ppt/096ac9c6d066.png",
  "steam-gift-card-50": "https://sfile.chatglm.cn/images-ppt/e1aa34ee4453.png",
  "netflix-gift-card-30": "https://sfile.chatglm.cn/images-ppt/d2dd33ebbd0d.png",
  "spotify-premium-3-month-card": "https://sfile.chatglm.cn/images-ppt/a19db06be964.jpg",
  "amazon-gift-card-100": "https://sfile.chatglm.cn/images-ppt/040bda060690.jpg",
};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    name: "NovaScript AI Writer",
    slug: "novascript-ai-writer",
    description: "GPT-powered long-form content engine for blogs & ads.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 59,
    oldPrice: 79,
    badge: "-25%",
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "PixelForge Image Generator",
    slug: "pixelforge-image-generator",
    description: "Diffusion-based image studio with style presets.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 99,
    oldPrice: 129,
    badge: "-23%",
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "VoxAI Voice Cloning Suite",
    slug: "voxai-voice-cloning-suite",
    description: "Studio-grade voice cloning & TTS in 32 languages.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 199,
    oldPrice: undefined,
    badge: undefined,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "DevGuard Pro License",
    slug: "devguard-pro-license",
    description: "Code security scanner with SAST + dependency analysis.",
    category: "software",
    brand: "Playbeat",
    price: 199,
    oldPrice: 249,
    badge: "-20%",
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "SheetFlow Automation",
    slug: "sheetflow-automation",
    description: "No-code workflows connecting 200+ apps. Monthly plan.",
    category: "subscriptions",
    brand: "Playbeat",
    price: 19,
    oldPrice: undefined,
    badge: undefined,
    icon: "Crown",
    gradient: "from-amber-500/80 to-yellow-500/80",
    stock: 999,
    featured: true,
  },
  {
    name: "InboxZen Email Marketing",
    slug: "inboxzen-email-marketing",
    description: "AI-assisted email campaigns with deliverability analytics.",
    category: "subscriptions",
    brand: "Playbeat",
    price: 29,
    oldPrice: 39,
    badge: "-26%",
    icon: "Crown",
    gradient: "from-amber-500/80 to-yellow-500/80",
    stock: 999,
    featured: false,
  },
  {
    name: "CineMaster LUTs Bundle",
    slug: "cinemaster-luts-bundle",
    description: "120 cinematic LUTs for Premiere, DaVinci & FCPX.",
    category: "digital-downloads",
    brand: "Playbeat",
    price: 49,
    oldPrice: undefined,
    badge: undefined,
    icon: "Download",
    gradient: "from-pink-500/80 to-purple-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "The Indie Maker Playbook",
    slug: "the-indie-maker-playbook",
    description: "320-page guide to building & launching SaaS solo.",
    category: "e-books",
    brand: "Playbeat",
    price: 15,
    oldPrice: 24,
    badge: "-38%",
    icon: "BookOpen",
    gradient: "from-sky-500/80 to-indigo-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "LaunchKit Landing Templates",
    slug: "launchkit-landing-templates",
    description: "12 conversion-optimized landing pages (React + Tailwind).",
    category: "templates",
    brand: "Playbeat",
    price: 59,
    oldPrice: undefined,
    badge: undefined,
    icon: "Layout",
    gradient: "from-violet-500/80 to-fuchsia-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Aurora Icon Set",
    slug: "aurora-icon-set",
    description: "2,400 vector icons in 6 styles, SVG + Figma.",
    category: "graphics",
    brand: "Playbeat",
    price: 25,
    oldPrice: 35,
    badge: "-29%",
    icon: "Palette",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Mastering Prompt Engineering",
    slug: "mastering-prompt-engineering",
    description: "8-hour video course + 60 prompt templates.",
    category: "courses",
    brand: "Playbeat",
    price: 99,
    oldPrice: 149,
    badge: "-34%",
    icon: "GraduationCap",
    gradient: "from-blue-500/80 to-cyan-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Founders Circle Membership",
    slug: "founders-circle-membership",
    description: "Monthly access to premium tools, community & drops.",
    category: "memberships",
    brand: "Playbeat",
    price: 89,
    oldPrice: undefined,
    badge: undefined,
    icon: "Users",
    gradient: "from-amber-600/80 to-orange-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "DataWave Analytics Platform",
    slug: "datawave-analytics-platform",
    description: "Real-time product analytics with funnel & retention.",
    category: "subscriptions",
    brand: "Playbeat",
    price: 99,
    oldPrice: undefined,
    badge: undefined,
    icon: "Crown",
    gradient: "from-amber-500/80 to-yellow-500/80",
    stock: 999,
    featured: false,
  },
  {
    name: "SynthWave Music Pack",
    slug: "synthwave-music-pack",
    description: "80 royalty-free synth loops & one-shots (WAV).",
    category: "digital-downloads",
    brand: "Playbeat",
    price: 29,
    oldPrice: undefined,
    badge: undefined,
    icon: "Download",
    gradient: "from-pink-500/80 to-purple-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "CloudVault Backup License",
    slug: "cloudvault-backup-license",
    description: "Encrypted incremental backups for servers & NAS.",
    category: "software",
    brand: "Playbeat",
    price: 69,
    oldPrice: undefined,
    badge: undefined,
    icon: "Code2",
    gradient: "from-emerald-500/80 to-teal-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "BriefBot AI Assistant",
    slug: "briefbot-ai-assistant",
    description: "Affiliate offer: 30% recurring commission.",
    category: "affiliate",
    brand: "Playbeat",
    price: 0,
    oldPrice: undefined,
    badge: "FREE",
    icon: "Share2",
    gradient: "from-slate-500/80 to-gray-600/80",
    stock: 9999,
    featured: false,
  },
  {
    name: "ResumeBoost AI Tool",
    slug: "resumeboost-ai-tool",
    description: "AI resume optimizer with ATS scoring.",
    category: "ai-tools",
    brand: "Playbeat",
    price: 9,
    oldPrice: undefined,
    badge: undefined,
    icon: "Sparkles",
    gradient: "from-cyan-500/80 to-blue-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "PitchDeck Pro Templates",
    slug: "pitchdeck-pro-templates",
    description: "30 investor pitch deck templates (PPTX + Figma).",
    category: "templates",
    brand: "Playbeat",
    price: 35,
    oldPrice: 45,
    badge: "-22%",
    icon: "Layout",
    gradient: "from-violet-500/80 to-fuchsia-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "CodeCraft Design Patterns",
    slug: "codecraft-design-patterns",
    description: "180-page guide to modern design patterns (TS/Go/Rust).",
    category: "e-books",
    brand: "Playbeat",
    price: 32,
    oldPrice: undefined,
    badge: undefined,
    icon: "BookOpen",
    gradient: "from-sky-500/80 to-indigo-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "PhotoFX Lightroom Presets",
    slug: "photofx-lightroom-presets",
    description: "60 Lightroom presets for portraits & landscapes.",
    category: "graphics",
    brand: "Playbeat",
    price: 19,
    oldPrice: undefined,
    badge: undefined,
    icon: "Palette",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Web3 Dev Bootcamp",
    slug: "web3-dev-bootcamp",
    description: "40-hour bootcamp: Solidity, smart contracts, dApps.",
    category: "courses",
    brand: "Playbeat",
    price: 199,
    oldPrice: undefined,
    badge: undefined,
    icon: "GraduationCap",
    gradient: "from-blue-500/80 to-cyan-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "TaskFlow PM Tool",
    slug: "taskflow-pm-tool",
    description: "Lightweight project management for small teams.",
    category: "subscriptions",
    brand: "Playbeat",
    price: 14,
    oldPrice: undefined,
    badge: undefined,
    icon: "Crown",
    gradient: "from-amber-500/80 to-yellow-500/80",
    stock: 999,
    featured: false,
  },
  {
    name: "RenderFarm GPU Credits",
    slug: "renderfarm-gpu-credits",
    description: "Affiliate offer: $20 credit per signup, 15% recurring.",
    category: "affiliate",
    brand: "Playbeat",
    price: 0,
    oldPrice: undefined,
    badge: "FREE",
    icon: "Share2",
    gradient: "from-slate-500/80 to-gray-600/80",
    stock: 9999,
    featured: false,
  },
  {
    name: "BrandKit Logo Bundle",
    slug: "brandkit-logo-bundle",
    description: "50 editable logo kits in SVG + AI formats.",
    category: "graphics",
    brand: "Playbeat",
    price: 39,
    oldPrice: 55,
    badge: "-29%",
    icon: "Palette",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Stripe Connect Integration Kit",
    slug: "stripe-connect-integration-kit",
    description: "Drop-in Stripe Connect checkout, subscriptions & marketplace splits.",
    category: "payment-gateways",
    brand: "Playbeat",
    price: 119,
    oldPrice: 149,
    badge: "-20%",
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "PayPal Checkout Pro",
    slug: "paypal-checkout-pro",
    description: "Smart PayPal buttons + Pay Later + vaulted cards.",
    category: "payment-gateways",
    brand: "Playbeat",
    price: 89,
    oldPrice: undefined,
    badge: undefined,
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Paddle Billing Suite",
    slug: "paddle-billing-suite",
    description: "Merchant-of-record billing, taxes & subscriptions handled.",
    category: "payment-gateways",
    brand: "Playbeat",
    price: 159,
    oldPrice: 199,
    badge: "-20%",
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Lemon Squeezy Storefront Pack",
    slug: "lemon-squeezy-storefront-pack",
    description: "Sell digital products & software with built-in licensing.",
    category: "payment-gateways",
    brand: "Playbeat",
    price: 79,
    oldPrice: undefined,
    badge: undefined,
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "CryptoPay Gateway",
    slug: "cryptopay-gateway",
    description: "Accept BTC, ETH, USDT & 40+ tokens with auto settlement.",
    category: "payment-gateways",
    brand: "Playbeat",
    price: 99,
    oldPrice: 129,
    badge: "-23%",
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Razorpay Route Integration",
    slug: "razorpay-route-integration",
    description: "UPI, cards, netbanking & EMI for the Indian market.",
    category: "payment-gateways",
    brand: "Playbeat",
    price: 69,
    oldPrice: undefined,
    badge: undefined,
    icon: "CreditCard",
    gradient: "from-green-500/80 to-emerald-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Neon Drift Racer",
    slug: "neon-drift-racer",
    description: "Synthwave arcade racer with 40 tracks & online leaderboards.",
    category: "games",
    brand: "Playbeat",
    price: 18,
    oldPrice: 24,
    badge: "-25%",
    icon: "Gamepad2",
    gradient: "from-violet-600/80 to-fuchsia-600/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Dungeon of Aether",
    slug: "dungeon-of-aether",
    description: "Roguelike dungeon crawler with procedural levels.",
    category: "games",
    brand: "Playbeat",
    price: 19,
    oldPrice: undefined,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-violet-600/80 to-fuchsia-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Pixel Kingdom Builder Kit",
    slug: "pixel-kingdom-builder-kit",
    description: "2D pixel-art kingdom builder engine + 500 sprites.",
    category: "games",
    brand: "Playbeat",
    price: 27,
    oldPrice: 34,
    badge: "-21%",
    icon: "Gamepad2",
    gradient: "from-violet-600/80 to-fuchsia-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Starbound Tactics",
    slug: "starbound-tactics",
    description: "Turn-based space strategy with fleet combat.",
    category: "games",
    brand: "Playbeat",
    price: 29,
    oldPrice: undefined,
    badge: undefined,
    icon: "Gamepad2",
    gradient: "from-violet-600/80 to-fuchsia-600/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Steam Gift Card $50",
    slug: "steam-gift-card-50",
    description: "Steam wallet top-up — redeem instantly worldwide.",
    category: "gift-cards",
    brand: "Playbeat",
    price: 50,
    oldPrice: undefined,
    badge: undefined,
    icon: "Gift",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Netflix Gift Card $30",
    slug: "netflix-gift-card-30",
    description: "Netflix subscription credit — works with any plan.",
    category: "gift-cards",
    brand: "Playbeat",
    price: 30,
    oldPrice: undefined,
    badge: undefined,
    icon: "Gift",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: false,
  },
  {
    name: "Spotify Premium 3-Month Card",
    slug: "spotify-premium-3-month-card",
    description: "3 months of Spotify Premium, ad-free music.",
    category: "gift-cards",
    brand: "Playbeat",
    price: 25,
    oldPrice: 29,
    badge: "-14%",
    icon: "Gift",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: true,
  },
  {
    name: "Amazon Gift Card $100",
    slug: "amazon-gift-card-100",
    description: "Amazon.com balance — shop millions of products.",
    category: "gift-cards",
    brand: "Playbeat",
    price: 100,
    oldPrice: undefined,
    badge: undefined,
    icon: "Gift",
    gradient: "from-rose-500/80 to-orange-500/80",
    stock: 999,
    featured: false,
  },
].map((p) => ({ ...p, image: PRODUCT_IMAGES[p.slug] }));
